accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import signup

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

projects/urls.py
from django.urls import path

from projects.views import (
    ProjectCreateView,
    ProjectListView,
    ProjectDetailView,
)

urlpatterns = [
    path("", ProjectListView.as_view(), name="list_projects"),
    path("<int:pk>/", ProjectDetailView.as_view(), name="show_project"),
    path("create/", ProjectCreateView.as_view(), name="create_project"),
]

tasks/urls.py
from django.urls import path

from tasks.views import TaskCreateView, TaskListView, TaskUpdateView

urlpatterns = [
    path("create/", TaskCreateView.as_view(), name="create_task"),
    path("mine/", TaskListView.as_view(), name="show_my_tasks"),
    path("<int:pk>/complete/", TaskUpdateView.as_view(), name="complete_task"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("projects/", include("projects.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("list_projects")),
        name="home",
    ),
    path("accounts/", include("accounts.urls")),
    path("tasks/", include("tasks.urls")),
]

projects/models.py
from django.db import models
from django.conf import settings


USER_MODEL = settings.AUTH_USER_MODEL


class Project(models.Model):
    class Priorities(models.TextChoices):
        LOW = "Low", "Low"
        MEDIUM = "Medium", "Medium"
        HIGH = "HIGH", "HIGH"

    # PRIORITIES = [
    #     (LOW, "Low"),
    #     (MEDIUM, "Medium"),
    #     (HIGH, "HIGH"),
    # ]
    name = models.CharField(max_length=200)
    description = models.TextField()
    members = models.ManyToManyField(USER_MODEL, related_name="projects")
    priority = models.CharField(
        max_length=10,
        choices=Priorities.choices,
        default=Priorities.LOW,
        blank=Priorities.LOW,
    )

    def __str__(self):
        return self.name

tasks/models.py
from django.db import models
from django.conf import settings


USER_MODEL = settings.AUTH_USER_MODEL


class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(
        "projects.Project", related_name="tasks", on_delete=models.CASCADE
    )
    assignee = models.ForeignKey(
        USER_MODEL, null=True, related_name="tasks", on_delete=models.SET_NULL
    )

    def __str__(self):
        return self.name

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username=username, password=password
            )
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm
    context = {"form": form}
    return render(request, "registration/signup.html", context)

projects/views.py
from django.views.generic.list import ListView
from django.views.generic import CreateView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from projects.models import Project


class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = "projects/list.html"

    def get_queryset(self):
        members_projects = Project.objects.filter(members=self.request.user)
        return members_projects


class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = "projects/detail.html"


class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Project
    template_name = "projects/create.html"
    fields = ["name", "description", "members", "priority"]

    def get_success_url(self):
        return reverse_lazy("show_project", args=[self.object.id])

tasks/views.py
from django.views.generic import CreateView, UpdateView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from tasks.models import Task


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    template_name = "tasks/create.html"
    fields = ["name", "start_date", "due_date", "project", "assignee"]

    def get_success_url(self):
        return reverse_lazy("show_project", args=[self.object.project.id])


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "tasks/list.html"

    def get_queryset(self):
        assignee_tasks = Task.objects.filter(
            assignee=self.request.user
        ).order_by("is_completed", "due_date")
        return assignee_tasks


class TaskUpdateView(UpdateView):
    model = Task
    template_name = "tasks/list.html"
    fields = ["is_completed"]
    success_url = reverse_lazy("show_my_tasks")

projects/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Tracker</title>
        <link rel="stylesheet" href="{% static 'css/tracker.css' %}">
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'show_my_tasks' %}">My tasks</a>
                        </li>
                        <li>
                            <a href="{% url 'list_projects' %}">Projects</a>
                        </li>
                        <li>
                            <a href="{% url 'logout' %}">Logout</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url 'login' %}">Login</a>
                        </li>
                        <li>
                            <a href="{% url 'signup' %}">Sign Up</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        {% block content %}
        {% endblock content %}
    </body>
</html>

projects/templates/projects/create.html
{% extends 'base.html' %}
{% block content %}
    <main>
        <div class="project-form">
            <h1>Create a new project</h1>
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button>Create</button>
            </form>
        </div>
    </main>
{% endblock content %}

projects/templates/projects/detail.html
{% extends 'base.html' %}
{% load markdownify %}
{% block content %}
    <main>
        <div class="project-detail">
            <h1>{{ project.name }} - Priority: {{ project.priority }}</h1>
            {{ project.description|markdownify }}
            {% comment %} {% for item in project.members.all %} {% endcomment %}
            <h2>{{ request.user | title }}'s Tasks</h2>
            {% comment %} {% endfor %} {% endcomment %}
            <p>
                <a href="{% url 'create_task' %}">Create a new task</a>
            </p>
            <table>
                {% if project.tasks.all %}
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Start date</th>
                            <th>Due date</th>
                            <th>Is completed</th>
                        </tr>
                    </thead>
                {% endif %}
                {% for task in project.tasks.all %}
                    <tbody>
                        <tr>
                            <td>{{ task.name }}</td>
                            <td>{{ task.start_date | date:"F d, o" }}</td>
                            <td>{{ task.due_date | date:"F d, o" }}</td>
                            <td>{{ task.is_completed | yesno }}</td>
                        </tr>
                    {% empty %}
                        <p>This project has no tasks</p>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </main>
{% endblock content %}

projects/templates/projects/list.html
{% extends 'base.html' %}
{% block content %}
    <main>
        <div class="project-list">
            <h1>My Projects</h1>
            <p>
                <a href="{% url 'create_project' %}">Create a new project</a>
            </p>
            {% if project_list %}
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Number of Tasks</th>
                        <th>Priority</th>
                    </tr>
                </thead>
                {% endif %}
                <tbody>
                    {% for project in project_list %}
                        <tr>
                            <td>
                                <a href="{% url 'show_project' project.pk %}">{{ project.name }}</a>
                            </td>
                            <td>{{ project.tasks.all | length }}</td>
                            <td>{{ project.priority }}</td>
                        </tr>
                    {% empty %}
                        <p>You are not assigned to any projects</p>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </main>
{% endblock content %}

tasks/templates/tasks/create.html
{% extends 'base.html' %}
{% block content %}
    <main>
        <div class="task-form">
            <h1>Create a new task</h1>
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button>Create</button>
            </form>
        </div>
    </main>
{% endblock content %}

tasks/templates/tasks/list.html
{% extends 'base.html' %}
{% block content %}
    <main>
        <div class="my-tasks-list">
            <h1>My Tasks</h1>
            {% if task_list %}
                <table>
                    <thead>
                        <tr>
                            <th>Project</th>
                            <th>Task</th>
                            <th>Start date</th>
                            <th>End date</th>
                            <th>Is completed</th>
                        </tr>
                    </thead>
                {% endif %}
                <tbody>
                    {% for task in task_list %}
                        <tr>
                            <td>{{ task.project }}</td>
                            <td>{{ task.name }}</td>
                            <td>{{ task.start_date }}</td>
                            <td>{{ task.due_date }}</td>
                            <td>{{ task.is_completed | yesno }}</td>
                            {% if task.is_completed == False %}
                            <td><form method="post" action="{% url 'complete_task' task.id %}">
                                    {% csrf_token %}
                                    <input type="hidden" name="is_completed" value="True">
                                    <button>Complete</button>
                                </form>
                            </td>
                            {% endif %}
                        </tr>
                    {% empty %}
                        <p>You have no tasks</p>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </main>
{% endblock content %}